# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-11 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(related_name='tags', to='blog.Post'),
        ),
    ]
